import type { PlannedOp } from './plan';
import { pascalIdent, snake } from './naming';

export const DO_NOT_EDIT = 'Generated by Connector Network — do not edit by hand.';

export function isIdent(name: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name);
}

/** Object key as written in TS source (bare if a valid identifier, else quoted). */
export function tsKey(name: string): string {
  return isIdent(name) ? name : JSON.stringify(name);
}

/** TS template-literal path with `{param}` segments substituted from a `params` object. */
export function tsPathTemplate(op: PlannedOp): string {
  const body = op.path.replace(
    /\{([^}]+)\}/g,
    (_m, name: string) => '${encodeURIComponent(String(params[' + JSON.stringify(name) + ']))}',
  );
  return '`' + body + '`';
}

/** A safe Python identifier for a field/param name (snake fallback when not a valid identifier). */
export function pyVar(name: string): string {
  return isIdent(name) ? name : snake(name) || '_arg';
}

/** Python path literal: a plain string, or an f-string when there are path params. */
export function pyPathLiteral(op: PlannedOp): string {
  if (op.pathParams.length === 0) return JSON.stringify(op.path);
  const body = op.path.replace(/\{([^}]+)\}/g, (_m, name: string) => '{quote(str(' + pyVar(name) + '))}');
  return 'f' + JSON.stringify(body);
}

export function paramsTypeName(opId: string): string {
  return pascalIdent(opId.replace(/^op_/, '')) + 'Params';
}
