/**
 * A tiny HTTP wrapper the studio writes next to a generated `cli.mjs` to host the CLI as a command
 * service: `POST /run {args:[…]}` spawns `node cli.mjs …args` (no shell) with the upstream env and
 * returns `{exitCode, stdout, stderr}`; `GET /health` for readiness. Zero dependencies. Bound to
 * 127.0.0.1 by the studio. The filename is unusual so it never collides with a generated file.
 */
export const CLI_HTTP_WRAPPER_FILENAME = '_cn_cli_http.mjs';

export const CLI_HTTP_WRAPPER = `#!/usr/bin/env node
// Generated by Connector Network — CLI-over-HTTP host wrapper. Do not edit.
import { createServer } from 'node:http';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const PORT = Number(process.env.PORT || 8000);
const HOST = process.env.HOST || '0.0.0.0';
const DIR = dirname(fileURLToPath(import.meta.url));
const CLI = join(DIR, 'cli.mjs');
const MAX_ARGS = 64;
const MAX_OUTPUT = 1_000_000;

function runCli(args) {
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn(process.execPath, [CLI, ...args], {
        cwd: DIR,
        env: { PATH: process.env.PATH, CN_BASE_URL: process.env.CN_BASE_URL, CN_TOKEN: process.env.CN_TOKEN },
      });
    } catch (e) {
      resolve({ exitCode: -1, stdout: '', stderr: String((e && e.message) || e) });
      return;
    }
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (c) => { if (stdout.length < MAX_OUTPUT) stdout += c; });
    child.stderr.on('data', (c) => { if (stderr.length < MAX_OUTPUT) stderr += c; });
    child.on('error', (e) => resolve({ exitCode: -1, stdout, stderr: stderr + String((e && e.message) || e) }));
    child.on('exit', (code) => resolve({ exitCode: code == null ? -1 : code, stdout, stderr }));
  });
}

const server = createServer((req, res) => {
  if (req.method === 'GET' && req.url === '/health') {
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ status: 'ok', cli: true }));
    return;
  }
  if (req.method !== 'POST' || (req.url || '').split('?')[0] !== '/run') {
    res.writeHead(404, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ error: 'POST /run {"args":[...]} or GET /health' }));
    return;
  }
  let data = '';
  req.on('data', (c) => { data += c; if (data.length > 256 * 1024) req.destroy(); });
  req.on('end', async () => {
    let args;
    try { args = (JSON.parse(data || '{}')).args; } catch { res.writeHead(400, { 'content-type': 'application/json' }); res.end(JSON.stringify({ error: 'invalid JSON' })); return; }
    if (!Array.isArray(args) || args.some((a) => typeof a !== 'string') || args.length > MAX_ARGS) {
      res.writeHead(400, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ error: 'args must be an array of strings (max ' + MAX_ARGS + ')' }));
      return;
    }
    const out = await runCli(args);
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify(out));
  });
});
server.listen(PORT, HOST, () => process.stdout.write('CLI (HTTP) on ' + HOST + ':' + PORT + ' — POST /run\\n'));
`;
